# Copyright 2021 OpenHW Group
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# Run functional regression checks
name: ci
on: [push, pull_request]

jobs:
  install-tools:
    name: install-tools
    runs-on: ubuntu-latest
    env:
      NUM_JOBS: 8
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install
      run: |
        make verilator riscv32-gcc bender; cd golden-model && source setup-py.sh

  run-tests:
    name: run-tests
    runs-on: ubuntu-latest
    env:
      REDMULE_COMPLEX: 0
    needs:
      install-tools
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

   - name: Run Tests
      run: |
        make verilator riscv32-gcc bender; cd golden-model && source setup-py.sh
        make golden M=12 N=16 K=16
        make sw-all
        make hw-all
